import libs = readerwriterqueue%lib{readerwriterqueue}

exe{driver}: common/{hxx cxx}{simplethread} unittests/hxx{minitest} unittests/cxx{unittests} $libs
exe{driver}: test.options = --disable-prompt
