lib{readerwriterqueue}: hxx{*}
{
  cxx.export.poptions += "-I$src_base"
}

if ($cxx.target.class == 'linux')
{
    lib{readerwriterqueue}: cxx.export.libs += "-lpthread"
}

../upstream/include/
{
  hxx{*}: install.subdirs = true
}
